### PR TITLE
feat: integrate interface inheritance

### PR DESCRIPTION
**Pull request by 0x-buidl**

### CODE REVIEW

**Comment by 0x-buidl** [comment]
Added embedded structs inheritance. 

[input file](examples/inheritance/inheritance.go)
[output file](examples/inheritance/index.ts)

**Comment by 0x-buidl** [comment]
> Really cool, thank you for this contribution.
> 
> I want to give this the attention it deserves, I'm posting this comment to make sure that I'm very much aware of it :)

Thank you!

**Review by gzuidhof — APPROVED** [review]
This is really fantastic, thank you. 

The only thing I would ask is if perhaps you could provide a small example for the README (so that people know they can add an `inline` tag and what that does).

I have fixed the goreleaser config, so if you merge master (or rebase) CI should be green too :)

**Comment by gzuidhof** [comment]
A small thought.. `extends` may be a more direct name than `inline`? Really happy either way: neither name is perfect..

**Comment by 0x-buidl** [comment]
Awesome! Will update the README. 

Regarding the `inline` vs `extends`, I stuck with `inline` because i've seen packages like `bson,json` use the tag for merging structs (a little conventional in my opinion ). That way either `json | tstype | yaml`  inline tags works. But I'm realizing this could conflict when they have custom implementations. I'll just make it more strict so user knows to explicitly set `tstype:,extends` that works only on structs.

**Comment by 0x-buidl** [comment]
I think this is ready for merge now.

**Comment by gzuidhof** [comment]
Amazing, thank you so much :) 

I took the opportunity to fix two other outstanding bugs in #33  and #32, will mint a release :)

**Pull request merged**
